"""Runtime-neutral port protocols."""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol, runtime_checkable

try:
    from scripts.clarification_protocol import (ClarificationSource, IngestResult, PublishResult,
                                                 ResponseSubmission)
except ImportError:  # installed Skill layout exposes sibling tools directly
    from clarification_protocol import (ClarificationSource, IngestResult, PublishResult,
                                        ResponseSubmission)
from .contracts import ActionIntent, SettlementEvent


@runtime_checkable
class AgentExecutionPort(Protocol):
    def capabilities(self) -> frozenset[str]: ...
    def start(self, intent: ActionIntent) -> Mapping[str, Any]: ...
    def send(self, intent_id: str, command: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def status(self, intent_id: str) -> Mapping[str, Any]: ...
    def interrupt(self, intent_id: str, reason: str) -> Mapping[str, Any]: ...
    def settlement(self, intent_id: str) -> SettlementEvent | None: ...


@runtime_checkable
class ArtifactStorePort(Protocol):
    def put(self, intent: ActionIntent, content: bytes) -> Mapping[str, Any]: ...
    def get(self, artifact_id: str) -> bytes: ...
    def evidence(self, evidence_id: str) -> bytes: ...


@runtime_checkable
class RuntimeStatePort(Protocol):
    def get_receipt(self, intent_id: str) -> Mapping[str, Any] | None: ...
    def claim(self, intent: ActionIntent) -> Mapping[str, Any]: ...
    def settle(self, intent_id: str, event: SettlementEvent) -> Mapping[str, Any]: ...


@runtime_checkable
class HumanApprovalPort(Protocol):
    def publish(self, *, run_id: str, sources: Sequence[ClarificationSource]) -> PublishResult: ...
    def show(self, *, run_id: str, request_id: str) -> Mapping[str, object]: ...
    def ingest(self, *, run_id: str, request_id: str, decision_item_id: str | None,
               submission: ResponseSubmission) -> IngestResult: ...


class ClockPort(Protocol):
    def now(self) -> str: ...


class IdGeneratorPort(Protocol):
    def stable_id(self, namespace: str, canonical_payload: bytes) -> str: ...
