#!/usr/bin/env python3
"""Run-scoped ORCHESTRATOR_LOG.md / TIMING_LOG.md writers.

OS-17: SKILL.md section 9's artifact path contract has always named these two
files as something a Run leaves behind under its own `<ARTIFACT_ROOT>`, but
nothing in the actual orchestration execution path ever wrote them -- a real
run produced phase/review artifacts and nothing else. This module is the
"small logging helper" section 6 of OS-17 asks for: it owns formatting and
appending, and reads everything it writes from data the caller already has
(a `RuntimeAttempt`, a lifecycle outcome, a timestamp pair) rather than
deriving anything new. It is deliberately not a telemetry subsystem -- no
aggregation, no analysis, no background writer, just two append-only markdown
tables under the run's own artifact root, sourced from state this repository
already tracks.

OS-17 review round 3 MAJOR-1: this file has ZERO imports from elsewhere in
scripts/ -- not even scripts.task_context -- on purpose. INSTALL.md's
documented global install (`cp -R orca-worker-reviewer-orchestration
~/.claude/skills/`) never copies scripts/, so a live Coordinator invoking this
module from an installed Skill in a target project that is not this
repository's own checkout would otherwise find no scripts.task_context to
import. This exact file is duplicated byte-for-byte at
orca-worker-reviewer-orchestration/tools/run_logging.py (parity enforced by
scripts/validate_skills.py's validate_run_logging_tool_parity), which is what
`cp -R` actually carries into an installed Skill. Edit this copy; the other
is generated by keeping the two identical, never by hand.

Standard library only, like every other module in scripts/.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable


ORCHESTRATOR_LOG_FILENAME = "ORCHESTRATOR_LOG.md"
TIMING_LOG_FILENAME = "TIMING_LOG.md"
# OS-19: the CLI path is a fresh process per event and therefore has no memory
# of when a dispatch started or which phase/iteration scope is open. That memory
# is the difference between a boundary that brackets its own dispatches and one
# that is stamped from a Coordinator's recollection, so it lives in a file next
# to the two logs it serves. The Python path (OrcaRuntimeHarness) is one long
# lived process and keeps the same state in memory instead -- same class, same
# transitions, only the storage differs.
TIMING_STATE_FILENAME = ".timing_state.json"

# The columns are the whole schema. Both tables are append-only and every row
# fills every column (blank string where a field does not apply to that
# event) so a later parser can split on `|` without special-casing rows.
ORCHESTRATOR_LOG_COLUMNS = (
    "timestamp",
    "event",
    "phase",
    "role",
    "iteration",
    "task_id",
    "dispatch_id",
    "terminal",
    "action",
    "reuse",
    "gate_result",
    "review_verdict",
    # OS-3. Sparse by design, the same way gate_result/review_verdict are: `risk` is
    # on run_start, every dispatch_settled, reviewer_gate_skipped and run_end;
    # `risk_source` on run_start and run_end; `requested_phases` on run_start;
    # `round_kind` on every dispatch_settled. Each answers a distinct question OS-3
    # asks these logs, and a column is machine-parseable where prose is not.
    "risk",
    "risk_source",
    "requested_phases",
    "round_kind",
    "result",
    "detail",
)
TIMING_LOG_COLUMNS = (
    "timestamp",
    "event",
    "phase",
    "role",
    "iteration",
    "started_at",
    "ended_at",
    "duration_s",
    # A duration is only interpretable against the strength that produced it.
    "risk",
    "detail",
)

# Section 2's four terminal run statuses. A fifth value is not a stricter
# status this module invented -- it is a caller passing something that is not
# one of the four the contract names, and that fails closed rather than being
# written as an unrecognized string a later reader has to guess about.
RUN_STATUS_VALUES = ("COMPLETED", "BLOCKED", "ERROR", "ESCALATED")
# OS-3 column vocabularies. Spelled here rather than imported: this module
# deliberately imports nothing from scripts/ (see the docstring), and the CLI's
# existing `--action` choices are the precedent for constraining a column this way.
RISK_VALUES = ("low", "medium", "high")
RISK_SOURCE_VALUES = ("explicit", "default")
ROUND_KIND_VALUES = (
    "phase_gate",
    "correction",
    "downstream_revalidation",
    "final_review",
)

# OS-19 fail-safe markers. A duration that cannot be measured leaves `duration_s`
# empty and appends one of these to the row's own `detail`, so "no duration" and
# "a duration that was thrown away because the input was impossible" are
# distinguishable by a later reader -- and by grep -- instead of both being a
# blank cell. They are appended to whatever `detail` the caller already had, never
# substituted for it.
TIMING_INVALID_ORDER = "timing_invalid=ended_at_before_started_at"
TIMING_INVALID_TIMESTAMP = "timing_invalid=unusable_timestamp"
TIMING_INVALID_DURATION = "timing_invalid=negative_duration_seconds"
TIMING_INVALID_MARKERS = (
    TIMING_INVALID_ORDER,
    TIMING_INVALID_TIMESTAMP,
    TIMING_INVALID_DURATION,
)

# The TIMING_LOG events RunTimingTracker owns the lifecycle of, as opposed to
# merely writing. Spelled once so the CLI and the tracker cannot disagree.
BOUNDARY_OPEN_EVENTS = ("phase_start", "iteration_start")
BOUNDARY_CLOSE_EVENTS = ("phase_end", "iteration_end")
DISPATCH_EVENTS = ("dispatch_settled", "unexpected_exit")


class RunLoggingError(ValueError):
    """Raised for a caller mistake (e.g. an unknown run status), never for I/O."""


def now_iso() -> str:
    """The one timestamp format both logs use: UTC, ISO-8601, sortable as text."""
    return datetime.now(timezone.utc).isoformat()


def resolve_duration(started_at: str, ended_at: str) -> tuple[float | str, str]:
    """`(duration_s, reason)` for one timestamp pair. Never raises.

    OS-19: `duration_s` is a measurement, and there is no such thing as a
    measurement of negative seconds. When the pair cannot produce one, the
    duration is "" and `reason` names why -- which is the whole point. PR #16's
    real OS-3 TIMING_LOG.md carries five rows whose `started_at` is minutes
    AFTER their `ended_at`, and the pre-OS-19 writer recorded the raw negative
    delta (-423s, -2267s, -1296s, -1998s, -2766s) as if it were a duration. It
    is neither clamped to 0 nor absolute-valued here: both would turn "this
    input was wrong" into a plausible-looking number that no later reader could
    tell apart from a real measurement.

    `reason` is "" both when the duration is valid and when there was simply
    nothing to compute (a missing side) -- an absent timestamp is a legitimate
    state (a `phase_start` row has no `ended_at` yet), not a fault to annotate.
    """
    if not started_at or not ended_at:
        return "", ""
    try:
        start = datetime.fromisoformat(started_at)
        end = datetime.fromisoformat(ended_at)
    except (TypeError, ValueError):
        return "", TIMING_INVALID_TIMESTAMP
    try:
        delta = (end - start).total_seconds()
    except TypeError:
        # Both sides parsed, but one is offset-naive and the other offset-aware,
        # so they are not comparable. Pre-OS-19 this raised out of
        # elapsed_seconds() -- and every caller invoked it OUTSIDE its own
        # _safe_log wrapper, so a logging concern aborted an already-settled
        # Dispatch. Section 9 (OS-17) forbids exactly that.
        return "", TIMING_INVALID_TIMESTAMP
    if delta < 0:
        return "", TIMING_INVALID_ORDER
    return delta, ""


def elapsed_seconds(started_at: str, ended_at: str) -> float | str:
    """`ended_at - started_at` in seconds, or "" when it cannot be measured.

    Never raises and never returns a negative number -- see resolve_duration(),
    which this delegates to and which also reports WHY a pair produced nothing.
    """
    return resolve_duration(started_at, ended_at)[0]


def _validate_duration(duration: Any) -> tuple[float | str, str]:
    """The same fail-safe judgement for a duration the caller computed itself.

    A caller that hands over `duration_seconds` directly (the `--duration-seconds`
    flag, or an offline reconstruction) bypasses resolve_duration() entirely, so
    a negative value would otherwise still reach the file through that door. A
    value that is not a number at all is passed through untouched: this function
    exists to catch impossible measurements, not to police the column's type.
    """
    if duration in ("", None):
        return "", ""
    try:
        value = float(duration)
    except (TypeError, ValueError):
        return duration, ""
    if value < 0:
        return "", TIMING_INVALID_DURATION
    return value, ""


def _escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def _ensure_table(path: Path, columns: tuple[str, ...]) -> None:
    """Write the header once. Never called again once the file exists.

    Idempotent the same way ensure_run_artifact_root() is: the header is
    written on first use and every later call is a pure append.
    """
    if path.exists():
        return
    header = "| " + " | ".join(columns) + " |\n"
    divider = "| " + " | ".join("---" for _ in columns) + " |\n"
    path.write_text(header + divider, encoding="utf-8")


def _append_row(path: Path, columns: tuple[str, ...], values: dict[str, Any]) -> None:
    row = "| " + " | ".join(_escape(values.get(column, "")) for column in columns) + " |\n"
    with path.open("a", encoding="utf-8") as handle:
        handle.write(row)


def _ensure_run_artifact_root(run_id: str, *, base: Path | None = None) -> Path:
    """Create artifacts/runs/<run_id>/ (under `base`, else the current directory
    -- never this file's own location) and return it.

    Deliberately re-implemented here rather than imported from
    scripts.task_context.ensure_run_artifact_root/run_artifact_root -- see the
    module docstring's OS-17 review round 3 MAJOR-1 note for why this file may
    not import anything else from scripts/. Behaviourally identical to the
    scripts.task_context versions on purpose: same fail-closed validation (no
    run_id, or one containing a path separator or a bare `.`/`..` segment,
    could escape artifacts/runs/ into an arbitrary path), same idempotent
    mkdir. `ArtifactRootParityTests` in test_run_logging.py checks the two stay
    behaviourally identical so this duplication cannot silently drift.
    """
    if not run_id:
        raise RunLoggingError(
            "run_id is required and must be the current Orca Run id; there is no "
            "fallback -- an artifact path without one would fall back to the shared "
            "artifacts/ root every other run also writes to"
        )
    if "/" in run_id or "\\" in run_id or run_id in (".", ".."):
        raise RunLoggingError(
            f"run_id must be a single path segment, got {run_id!r}; a value "
            "containing a path separator or '.'/'..' could escape artifacts/runs/"
        )
    root = (Path(base) if base is not None else Path(".")) / "artifacts" / "runs" / run_id
    root.mkdir(parents=True, exist_ok=True)
    return root


def orchestrator_log_path(run_id: str, *, base: Path | None = None) -> Path:
    """artifacts/runs/<run_id>/ORCHESTRATOR_LOG.md, provisioning the run root."""
    return _ensure_run_artifact_root(run_id, base=base) / ORCHESTRATOR_LOG_FILENAME


def timing_log_path(run_id: str, *, base: Path | None = None) -> Path:
    """artifacts/runs/<run_id>/TIMING_LOG.md, provisioning the run root."""
    return _ensure_run_artifact_root(run_id, base=base) / TIMING_LOG_FILENAME


def log_orchestrator_event(
    run_id: str,
    *,
    base: Path | None = None,
    event: str,
    phase: str = "",
    role: str = "",
    iteration: int | str = "",
    task_id: str = "",
    dispatch_id: str = "",
    terminal: str = "",
    action: str = "",
    reuse: str = "",
    gate_result: str = "",
    review_verdict: str = "",
    risk: str = "",
    risk_source: str = "",
    requested_phases: str = "",
    round_kind: str = "",
    result: str = "",
    detail: str = "",
    timestamp: str | None = None,
) -> Path:
    """Append one row to this run's ORCHESTRATOR_LOG.md. Returns the file path.

    `gate_result` and `review_verdict` are two different, non-substitutable answers
    to "did this review pass?", both already parsed out of the settled dispatch's own
    body -- neither is `result`'s `outcome=...`, which only says the dispatch/process
    settled successfully (a Reviewer settles just as successfully on FAIL as on PASS,
    the normal correction-loop case, so `outcome=succeeded` alone answers neither
    question). `gate_result` is the two-valued workflow gate (`RESULT: PASS|FAIL`)
    that actually drives the correction loop. `review_verdict` is OS-1's separate
    four-valued report annotation (`REVIEW_VERDICT: PASS|PASS WITH NOTES|FAIL|
    BLOCKED`) -- a richer distinction the two-valued gate collapses (PASS WITH NOTES
    into PASS, BLOCKED into FAIL) but that this column preserves. Both are blank for
    non-reviewer dispatches and for any event whose body never wrote a recognizable
    line for that field.
    """
    path = orchestrator_log_path(run_id, base=base)
    _ensure_table(path, ORCHESTRATOR_LOG_COLUMNS)
    _append_row(
        path,
        ORCHESTRATOR_LOG_COLUMNS,
        {
            "timestamp": timestamp or now_iso(),
            "event": event,
            "phase": phase,
            "role": role,
            "iteration": iteration,
            "task_id": task_id,
            "dispatch_id": dispatch_id,
            "terminal": terminal,
            "action": action,
            "reuse": reuse,
            "gate_result": gate_result,
            "review_verdict": review_verdict,
            "risk": risk,
            "risk_source": risk_source,
            "requested_phases": requested_phases,
            "round_kind": round_kind,
            "result": result,
            "detail": detail,
        },
    )
    return path


def log_timing_event(
    run_id: str,
    *,
    base: Path | None = None,
    event: str,
    phase: str = "",
    role: str = "",
    iteration: int | str = "",
    started_at: str = "",
    ended_at: str = "",
    duration_seconds: float | str = "",
    risk: str = "",
    detail: str = "",
    timestamp: str | None = None,
) -> Path:
    """Append one row to this run's TIMING_LOG.md. Returns the file path.

    `duration_seconds` is optional. When the caller supplies both `started_at` and
    `ended_at` but omits (or leaves blank) `duration_seconds`, it is derived here via
    `elapsed_seconds()` -- the same computation the Python harness path used to do at
    every call site. Deriving it once, in the writer both paths share, is what keeps
    a live Coordinator's `timing-event` CLI calls (which only ever had timestamps to
    give it) numerically identical to `OrcaRuntimeHarness`'s own rows, instead of the
    CLI path silently leaving `duration_s` blank while the Python path filled it in.
    An explicit `duration_seconds` (including `0.0`) is never overridden.

    OS-19: whichever door the duration comes through, it is the same fail-safe
    judgement -- an impossible measurement (an `ended_at` before its
    `started_at`, an unusable timestamp, a negative explicit duration) leaves
    `duration_s` empty and appends a `timing_invalid=...` marker to `detail`
    rather than writing a number no reader could trust. This function still
    never raises: it is logging, and section 9 (OS-17) requires that a logging
    concern cannot change a lifecycle decision that has already been made.
    """
    path = timing_log_path(run_id, base=base)
    _ensure_table(path, TIMING_LOG_COLUMNS)
    if duration_seconds in ("", None):
        duration, reason = resolve_duration(started_at, ended_at)
    else:
        duration, reason = _validate_duration(duration_seconds)
    if isinstance(duration, float):
        duration = f"{duration:.3f}"
    if reason:
        detail = f"{detail} {reason}".strip() if detail else reason
    _append_row(
        path,
        TIMING_LOG_COLUMNS,
        {
            "timestamp": timestamp or now_iso(),
            "event": event,
            "phase": phase,
            "role": role,
            "iteration": iteration,
            "started_at": started_at,
            "ended_at": ended_at,
            "duration_s": duration,
            "risk": risk,
            "detail": detail,
        },
    )
    return path


def log_run_status(
    run_id: str,
    status: str,
    *,
    base: Path | None = None,
    reason: str = "",
    run_started_at: str = "",
    risk: str = "",
    risk_source: str = "",
) -> None:
    """The one run-end event: one ORCHESTRATOR_LOG row, one TIMING_LOG row.

    `status` is fail-closed against RUN_STATUS_VALUES -- an unrecognized value
    is a caller bug, not a status this file should record as if it were valid.
    """
    if status not in RUN_STATUS_VALUES:
        raise RunLoggingError(
            f"unknown run status: {status!r}; expected one of {RUN_STATUS_VALUES}"
        )
    ended_at = now_iso()
    log_orchestrator_event(
        run_id,
        base=base,
        event="run_end",
        risk=risk,
        risk_source=risk_source,
        result=status,
        detail=reason,
        timestamp=ended_at,
    )
    log_timing_event(
        run_id,
        base=base,
        event="run_end",
        started_at=run_started_at,
        ended_at=ended_at,
        # OS-19: derived inside log_timing_event, the one place that applies the
        # fail-safe judgement. Computing it here as well would be a second
        # derivation that could disagree with the writer's -- and would put a
        # `(end - start)` outside the writer, where a TypeError on a naive/aware
        # pair escapes into the caller instead of staying a blank cell.
        risk=risk,
        detail=status,
        timestamp=ended_at,
    )


# ---- OS-19: the authoritative clock and the phase/iteration boundary lifecycle ----


class RunTimingTracker:
    """One run's open phase/iteration scopes and its pending dispatch clocks.

    OS-19. Before this existed, the boundary lifecycle lived only inside
    `OrcaRuntimeHarness` (Python path) and the CLI path had none at all -- it is
    a fresh process per event, so a live Coordinator following SKILL.md section
    9 had to supply `--started-at`/`--ended-at` from memory. It has no clock, and
    in PR #16's real OS-3 run it did what anything without a clock does: it
    chained each dispatch's `started_at` off the PREVIOUS row's `ended_at`, which
    was itself an estimate and frequently in the future. Five `dispatch_settled`
    rows came out with `started_at` minutes after `ended_at`, and every single
    `iteration_end`/`phase_end` row in that log has an empty `started_at` and a
    blank `duration_s`, because nothing remembered where the scope began.

    So this class owns two things, and both paths use the same one:

    1. The authoritative clock. `mark_dispatch_started()` reads `now_iso()` at
       the moment the dispatch actually starts and keeps it until that dispatch
       settles. Nothing downstream reconstructs it.
    2. The boundary lifecycle. A scope opens at the `opened_at` of the first
       dispatch inside it -- before that dispatch runs, so it brackets rather
       than trails it -- and closes at that scope's OWN last recorded activity,
       never at "now", which at transition time really means "whenever the next
       scope's dispatch happened to settle" and would fold the next scope's time
       into the outgoing one's duration.

    State lives in memory. `load()`/`save()` add a JSON round-trip through the
    run's own artifact root for the CLI path, whose process ends after every
    event; `OrcaRuntimeHarness` holds one instance for the life of the run and
    never persists. Same class, same transitions, so the two paths cannot drift.

    `emit` is the injected writer. `OrcaRuntimeHarness` passes one that routes
    through its `_safe_log`, which is what keeps section 9's "logging never
    changes lifecycle correctness" true for every row this class produces.
    """

    def __init__(
        self,
        run_id: str,
        *,
        base: Path | None = None,
        emit: Callable[..., Any] | None = None,
        risk: str = "",
    ) -> None:
        self.run_id = run_id
        self.base = base
        self.risk = risk
        self._emit = emit if emit is not None else self._write_row
        self.run_started_at: str = ""
        self.open_phase: str = ""
        self.phase_started_at: str = ""
        self.phase_result: str = ""
        self.phase_last_ended_at: str = ""
        self.open_iteration: tuple[str, str] | None = None
        self.iteration_started_at: str = ""
        self.iteration_result: str = ""
        self.iteration_last_ended_at: str = ""
        # "<phase>|<role>|<iteration>" -> the started_at this tracker captured.
        self.dispatch_marks: dict[str, str] = {}

    # ---- writer ------------------------------------------------------------

    def _write_row(self, **fields: Any) -> None:
        log_timing_event(self.run_id, base=self.base, **fields)

    # ---- authoritative clock -----------------------------------------------

    @staticmethod
    def dispatch_key(phase: str, role: str, iteration: int | str) -> str:
        return f"{phase}|{role}|{iteration}"

    def mark_dispatch_started(
        self,
        *,
        phase: str,
        role: str,
        iteration: int | str,
        started_at: str | None = None,
    ) -> str:
        """Capture (and return) the instant this dispatch starts.

        `started_at` is an override for a caller that already holds the same
        authoritative instant -- `OrcaRuntimeHarness` reads `now_iso()` itself
        immediately before `start_worker()` and hands that exact value to both
        this tracker and the eventual `dispatch_settled` row, so the two cannot
        differ. Nobody else supplies it.
        """
        captured = started_at or now_iso()
        self.dispatch_marks[self.dispatch_key(phase, role, iteration)] = captured
        return captured

    def take_dispatch_mark(
        self, *, phase: str, role: str, iteration: int | str
    ) -> str:
        """The captured start for this dispatch, consumed so a re-dispatch of the
        same (phase, role, iteration) gets its own mark rather than the last one's.
        """
        return self.dispatch_marks.pop(self.dispatch_key(phase, role, iteration), "")

    # ---- boundary lifecycle -------------------------------------------------

    def open_boundary(
        self, phase: str, iteration: int | str | None, *, opened_at: str
    ) -> None:
        """Open this dispatch's phase/iteration scope, closing whatever it replaces.

        Idempotent for a scope that is already open, so a Coordinator that marks
        every dispatch (the normal case) and one that also writes an explicit
        `phase_start` row do not produce two.
        """
        if not self.run_id or not phase:
            return
        if phase != self.open_phase:
            # The outgoing scopes close at their own last activity. `opened_at`
            # is the fallback for a scope nothing ever settled inside: it is the
            # same authoritative instant this transition is happening at, not a
            # second, slightly later clock read.
            self.close_iteration(ended_at=self.iteration_last_ended_at or opened_at)
            self.close_phase(ended_at=self.phase_last_ended_at or opened_at)
            self.open_phase = phase
            self.phase_started_at = opened_at
            self.phase_result = ""
            self.phase_last_ended_at = ""
            self._emit(
                event="phase_start",
                phase=phase,
                started_at=opened_at,
                risk=self.risk,
                timestamp=opened_at,
            )
        if iteration is None or iteration == "":
            return
        iteration_key = (phase, str(iteration))
        if iteration_key != self.open_iteration:
            self.close_iteration(ended_at=self.iteration_last_ended_at or opened_at)
            self.open_iteration = iteration_key
            self.iteration_started_at = opened_at
            self.iteration_result = ""
            self.iteration_last_ended_at = ""
            self._emit(
                event="iteration_start",
                phase=phase,
                iteration=iteration,
                started_at=opened_at,
                risk=self.risk,
                timestamp=opened_at,
            )

    def record_scope_activity(self, *, ended_at: str, result: str = "") -> None:
        """A dispatch inside the currently open scope settled at `ended_at`.

        This is what lets a scope close at its own last real activity. `result`
        is the most recent reviewer gate result seen inside the scope and
        becomes the eventual `iteration_end`/`phase_end` row's `detail`; a
        Worker attempt leaves it unchanged but still advances the end time.
        """
        if ended_at:
            self.iteration_last_ended_at = ended_at
            self.phase_last_ended_at = ended_at
        if result:
            self.iteration_result = result
            self.phase_result = result

    def close_iteration(
        self, *, ended_at: str | None = None, result: str | None = None
    ) -> None:
        if self.open_iteration is None:
            return
        phase, iteration = self.open_iteration
        ended = ended_at or self.iteration_last_ended_at or now_iso()
        self._emit(
            event="iteration_end",
            phase=phase,
            iteration=iteration,
            started_at=self.iteration_started_at,
            ended_at=ended,
            risk=self.risk,
            detail=self.iteration_result if result is None else result,
            timestamp=ended,
        )
        self.open_iteration = None
        self.iteration_started_at = ""
        self.iteration_result = ""
        self.iteration_last_ended_at = ""

    def close_phase(
        self, *, ended_at: str | None = None, result: str | None = None
    ) -> None:
        if not self.open_phase:
            return
        # The iteration inside it closes at ITS own last activity, not at the
        # phase's -- a phase_end supplied from outside must not retro-stamp the
        # iteration it happens to contain.
        self.close_iteration()
        ended = ended_at or self.phase_last_ended_at or now_iso()
        self._emit(
            event="phase_end",
            phase=self.open_phase,
            started_at=self.phase_started_at,
            ended_at=ended,
            risk=self.risk,
            detail=self.phase_result if result is None else result,
            timestamp=ended,
        )
        self.open_phase = ""
        self.phase_started_at = ""
        self.phase_result = ""
        self.phase_last_ended_at = ""

    def close_all(self, *, ended_at: str | None = None) -> None:
        """Close whatever is still open when the run ends.

        The common case: nothing in a normal flow closes the LAST phase and
        iteration, because there is no next scope whose transition would do it.
        """
        self.close_iteration(ended_at=ended_at or self.iteration_last_ended_at or None)
        self.close_phase(ended_at=ended_at or self.phase_last_ended_at or None)

    # ---- persistence (the CLI path's substitute for a long-lived process) ----

    def state_path(self) -> Path:
        return _ensure_run_artifact_root(self.run_id, base=self.base) / TIMING_STATE_FILENAME

    _PERSISTED = (
        "run_started_at",
        "open_phase",
        "phase_started_at",
        "phase_result",
        "phase_last_ended_at",
        "iteration_started_at",
        "iteration_result",
        "iteration_last_ended_at",
        "dispatch_marks",
    )

    @classmethod
    def load(
        cls,
        run_id: str,
        *,
        base: Path | None = None,
        emit: Callable[..., Any] | None = None,
        risk: str = "",
    ) -> "RunTimingTracker":
        """Read this run's tracker state, or start an empty one.

        Unreadable or corrupt state is an empty tracker, never an exception: a
        run whose state file was truncated still has to be able to log, and
        section 9 does not let a logging concern stop the run.
        """
        tracker = cls(run_id, base=base, emit=emit, risk=risk)
        try:
            raw = json.loads(tracker.state_path().read_text(encoding="utf-8"))
        except (OSError, ValueError):  # RunLoggingError is a ValueError
            return tracker
        if not isinstance(raw, dict):
            return tracker
        for name in cls._PERSISTED:
            value = raw.get(name)
            if isinstance(value, (str, dict)):
                setattr(tracker, name, value)
        open_iteration = raw.get("open_iteration")
        if isinstance(open_iteration, list) and len(open_iteration) == 2:
            tracker.open_iteration = (str(open_iteration[0]), str(open_iteration[1]))
        return tracker

    def save(self) -> None:
        """Persist this run's tracker state. Never raises, for the same reason."""
        payload: dict[str, Any] = {name: getattr(self, name) for name in self._PERSISTED}
        payload["open_iteration"] = (
            list(self.open_iteration) if self.open_iteration else None
        )
        try:
            self.state_path().write_text(
                json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
            )
        except (OSError, ValueError):  # RunLoggingError is a ValueError
            return


# ---- CLI: the same three writers, for a Coordinator driving Orca by hand ----------
# OrcaRuntimeHarness calls the functions above directly from Python. A live
# Coordinator following SKILL.md's own procedure drives Orca through `orca ...`
# Bash commands instead and has no Python object to call into -- this is that
# same logging reused from the other side of that gap, not a second
# implementation. `--base` defaults to the current directory (no override, no
# flag passed), so `python3 scripts/run_logging.py ... --run-id <id>` run from
# the repository root writes to the real artifacts/runs/<run-id>/, exactly
# where SKILL.md section 9 already says every run-scoped artifact lives.


def _add_common_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--base", default=None, help="defaults to the current directory")
    parser.add_argument("--phase", default="")
    parser.add_argument("--role", default="")
    parser.add_argument("--iteration", default="")


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="run_logging.py",
        description=(
            "Append one row to this run's ORCHESTRATOR_LOG.md or TIMING_LOG.md. "
            "For a live Coordinator driving Orca by hand; OrcaRuntimeHarness calls "
            "the same functions directly and does not need this CLI."
        ),
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    orchestrator = subparsers.add_parser(
        "orchestrator-event", help="append a row to ORCHESTRATOR_LOG.md"
    )
    _add_common_arguments(orchestrator)
    orchestrator.add_argument("--event", required=True)
    orchestrator.add_argument("--task-id", default="")
    orchestrator.add_argument("--dispatch-id", default="")
    orchestrator.add_argument("--terminal", default="")
    orchestrator.add_argument("--action", default="", choices=("", "created", "reused"))
    orchestrator.add_argument("--reuse", default="")
    orchestrator.add_argument("--gate-result", default="")
    orchestrator.add_argument("--review-verdict", default="")
    orchestrator.add_argument("--risk", default="", choices=("", *RISK_VALUES))
    orchestrator.add_argument(
        "--risk-source", default="", choices=("", *RISK_SOURCE_VALUES)
    )
    orchestrator.add_argument("--requested-phases", default="")
    orchestrator.add_argument(
        "--round-kind", default="", choices=("", *ROUND_KIND_VALUES)
    )
    orchestrator.add_argument("--result", default="")
    orchestrator.add_argument("--detail", default="")

    timing = subparsers.add_parser("timing-event", help="append a row to TIMING_LOG.md")
    _add_common_arguments(timing)
    timing.add_argument("--event", required=True)
    timing.add_argument("--started-at", default="")
    timing.add_argument("--ended-at", default="")
    timing.add_argument("--duration-seconds", default="")
    timing.add_argument("--risk", default="", choices=("", *RISK_VALUES))
    timing.add_argument("--detail", default="")

    dispatch_start = subparsers.add_parser(
        "timing-dispatch-start",
        help=(
            "capture the authoritative start of one dispatch and open its "
            "phase/iteration boundary; run this immediately before worker-start"
        ),
    )
    _add_common_arguments(dispatch_start)
    dispatch_start.add_argument("--risk", default="", choices=("", *RISK_VALUES))

    status = subparsers.add_parser(
        "run-status", help="append the one run-end row to both logs"
    )
    status.add_argument("--run-id", required=True)
    status.add_argument("--base", default=None, help="defaults to the current directory")
    status.add_argument("--status", required=True, choices=RUN_STATUS_VALUES)
    status.add_argument("--reason", default="")
    status.add_argument("--run-started-at", default="")
    status.add_argument("--risk", default="", choices=("", *RISK_VALUES))
    status.add_argument(
        "--risk-source", default="", choices=("", *RISK_SOURCE_VALUES)
    )

    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    base = Path(args.base) if args.base else None
    if args.command == "orchestrator-event":
        path = log_orchestrator_event(
            args.run_id,
            base=base,
            event=args.event,
            phase=args.phase,
            role=args.role,
            iteration=args.iteration,
            task_id=args.task_id,
            dispatch_id=args.dispatch_id,
            terminal=args.terminal,
            action=args.action,
            reuse=args.reuse,
            gate_result=args.gate_result,
            review_verdict=args.review_verdict,
            risk=args.risk,
            risk_source=args.risk_source,
            requested_phases=args.requested_phases,
            round_kind=args.round_kind,
            result=args.result,
            detail=args.detail,
        )
    elif args.command == "timing-dispatch-start":
        # OS-19: the authoritative dispatch clock for the CLI path. The
        # Coordinator does not pass a timestamp here and never has to remember
        # one later -- this command reads now_iso() at the moment the dispatch
        # actually starts, and the matching `timing-event --event
        # dispatch_settled` reads the mark back. That is the whole fix for the
        # five negative rows in PR #16's real OS-3 TIMING_LOG.md, every one of
        # which had a `started_at` reconstructed from an earlier row's estimate.
        tracker = RunTimingTracker.load(args.run_id, base=base, risk=args.risk)
        started_at = tracker.mark_dispatch_started(
            phase=args.phase, role=args.role, iteration=args.iteration
        )
        tracker.open_boundary(args.phase, args.iteration, opened_at=started_at)
        tracker.save()
        print(started_at)
        return 0
    elif args.command == "timing-event":
        path = _cli_timing_event(args, base)
    else:
        tracker = RunTimingTracker.load(args.run_id, base=base, risk=args.risk)
        # The Python path closes whatever scope is still open in finish(),
        # immediately before log_run_status(). Same order here, so a run that
        # ends mid-phase leaves a closed boundary rather than a dangling one.
        tracker.close_all()
        log_run_status(
            args.run_id,
            args.status,
            base=base,
            reason=args.reason,
            # A run's own start was captured by `timing-event --event run_start`
            # hours earlier; asking the Coordinator to hand it back is asking it
            # to remember a timestamp, which is what OS-19 is about.
            run_started_at=args.run_started_at or tracker.run_started_at,
            risk=args.risk,
            risk_source=args.risk_source,
        )
        tracker.save()
        path = orchestrator_log_path(args.run_id, base=base)
    print(path)
    return 0


def _cli_timing_event(args: argparse.Namespace, base: Path | None) -> Path:
    """`timing-event`, routed through this run's RunTimingTracker.

    The tracker owns the phase/iteration lifecycle and the dispatch clock, so
    the CLI path produces the same boundary rows, with the same bracketing and
    the same next-scope exclusion, that OrcaRuntimeHarness produces in-process.
    An explicit `--started-at`/`--ended-at` is still honoured -- an offline
    reconstruction is a legitimate use -- but it is validated identically, so
    the OS-3 failure cannot return through that door.
    """
    tracker = RunTimingTracker.load(args.run_id, base=base, risk=args.risk)
    path = timing_log_path(args.run_id, base=base)
    event = args.event
    started_at = args.started_at
    ended_at = args.ended_at

    if event in DISPATCH_EVENTS:
        started_at = started_at or tracker.take_dispatch_mark(
            phase=args.phase, role=args.role, iteration=args.iteration
        )
        ended_at = ended_at or now_iso()
        # A Coordinator that skipped `timing-dispatch-start` still gets a
        # bracketing boundary: opening here is idempotent for a scope that is
        # already open, and uses this dispatch's own start, never "now".
        tracker.open_boundary(args.phase, args.iteration, opened_at=started_at)
        log_timing_event(
            args.run_id,
            base=base,
            event=event,
            phase=args.phase,
            role=args.role,
            iteration=args.iteration,
            started_at=started_at,
            ended_at=ended_at,
            duration_seconds=args.duration_seconds,
            risk=args.risk,
            detail=args.detail,
        )
        tracker.record_scope_activity(ended_at=ended_at)
    elif event == "phase_start":
        tracker.open_boundary(args.phase, None, opened_at=started_at or now_iso())
    elif event == "iteration_start":
        tracker.open_boundary(
            args.phase, args.iteration, opened_at=started_at or now_iso()
        )
    elif event == "iteration_end":
        tracker.close_iteration(ended_at=ended_at or None, result=args.detail or None)
    elif event == "phase_end":
        tracker.close_phase(ended_at=ended_at or None, result=args.detail or None)
    else:
        if event == "run_start":
            tracker.run_started_at = started_at or now_iso()
            started_at = tracker.run_started_at
        log_timing_event(
            args.run_id,
            base=base,
            event=event,
            phase=args.phase,
            role=args.role,
            iteration=args.iteration,
            started_at=started_at,
            ended_at=ended_at,
            duration_seconds=args.duration_seconds,
            risk=args.risk,
            detail=args.detail,
        )
    tracker.save()
    return path


if __name__ == "__main__":
    sys.exit(main())
